### ISSUE TITLE
an integer is required

### ISSUE THREAD

**Issue by bravekingzhang** [interhui/py-xml#1]
```
 python setup.py install
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    with open('README.md', 'r', 'utf-8') as fp:
TypeError: an integer is required
```

**Comment by chennareddy08** [comment]
Yes ,
I have also faced same issue python3.7.1

C:\Windows\system32>pip install py-xml
Collecting py-xml
  Using cached https://files.pythonhosted.org/packages/90/02/4a3cf06d254c70334eb
f028e0bcd595c6f265ce1f1ed752bf2957dd8ba08/py-xml-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\cbiradar\AppData\Local\Temp\pip-install-9os2u613\py-xml\set
up.py", line 9, in <module>
        with open('README.md', 'r', 'utf-8') as fp:
    TypeError: an integer is required (got type str)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\cbiradar
\AppData\Local\Temp\pip-install-9os2u613\py-xml\

**Comment by jeffwright13** [comment]
This error is happening because the `open` command in setup.py (line 9) is positionally specifying "utf-8" as its third parameter. According to [the documentation](https://docs.python.org/3/library/functions.html#open), `open`'s third positional parameter (`buffering`) is expecting an integer. It's the fourth positional parameter that can accept the encoding string "utf-8", which seems to be the intent here.

The only way I can see to get around this issue (unless the author fixes it and releases a new version) would be to clone the repo locally, change line 9 of `setup.py` to 
```
with open('README.md', 'r', encoding='utf-8') as fp:
```
and then from the virtual environment that you want to install the library into, install it using `pip install -e <path-to-py-xml-repo>`.
